spring:
  application:
    name: chat_app
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatisConfig.xml